apiVersion: v1
kind: Namespace
metadata:
  name: langchain-namespace

---
apiVersion: v1
kind: Service
metadata:
  name: langchain-service
  namespace: langchain-namespace
spec:
  selector:
    app: langchain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-deployment
  namespace: langchain-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langchain
  template:
    metadata:
      labels:
        app: langchain
    spec:
      containers:
      - name: langchain
        image: cda-langchain-system:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: langchain-config
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: langchain-config
  namespace: langchain-namespace
data:
  # Define your configuration and environment variables here
  DATABASE_URL: "jdbc:mysql://your-database-url:3306/langchain"
  ANOTHER_ENV_VAR: "value"
